import cn.code91.facility.id.support.SnowIdGenerator;

/** Fixed stored values; verified on unchanged0ee9d54, not generated by the parser under test. */
public class LegacyIdSamples {
    public static void main(String[] args) {
        var defaultEpoch = new SnowIdGenerator(2, 3, 1_735_660_800_000L);
        check(defaultEpoch.parseTimestamp(163851281L) == 1_735_660_810_000L, "stored timestamp");
        check(SnowIdGenerator.parseDataCenterId(163851281L) == 2, "stored data center");
        check(SnowIdGenerator.parseWorkerId(163851281L) == 3, "stored worker");
        check(SnowIdGenerator.parseSequence(163851281L) == 17, "stored sequence");
        check(defaultEpoch.parseTimestamp(0) == 1_735_660_800_000L, "zero is representable");
        long maximum = 36028797018963967L;
        check(defaultEpoch.parseTimestamp(maximum) == 3_934_684_055_551L, "41-bit end timestamp");
        check(SnowIdGenerator.parseDataCenterId(maximum) == 3 && SnowIdGenerator.parseWorkerId(maximum) == 3
                && SnowIdGenerator.parseSequence(maximum) == 1023, "55-bit maximum components");
        check(new SnowIdGenerator(0, 0, -1000).parseTimestamp(16384000L) == 0, "historical negative epoch");
        check(defaultEpoch.parseTimestamp(-1) == 1_735_660_799_999L, "legacy parsing is not validation");
        System.out.println("LEGACY_ID_SAMPLES_PASS stored=163851281 maximum=36028797018963967 zero=0 negativeEpoch=-1000");
    }
    static void check(boolean condition, String message) { if (!condition) throw new AssertionError(message); }
}
